### ISSUE TITLE
Forms with file upload

### ISSUE THREAD

**Issue by dbd5** [claviska/jquery-ajaxSubmit#1]
Hi,

Could you advise on how to modify this plugin to support uploading file attachments with the form data?

Thanks

**Comment by claviska** [comment]
I don't [currently] have plans to extend the plugin to feature this, but it's possible for modern browsers using the FileReader API. [This answer](http://stackoverflow.com/a/11399659/567486) should get you started.

**Comment by dbd5** [comment]
Thanks for the response.
It seems that browser support for file upload is not consistent outside html5 and even html5 is not uniformly supported by the browsers.
I think you could extend the plugin in that direction when you have some time
